version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/task"
  mongo:
    image: mongo:6
    container_name: task-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
